@echo off
echo Downloading Node.js...
curl.exe -s -L -o node.zip https://nodejs.org/dist/v20.12.2/node-v20.12.2-win-x64.zip
echo Extracting Node.js...
tar.exe -xf node.zip
set PATH=%CD%\node-v20.12.2-win-x64;%PATH%
echo Running npm install...
call npm install
echo Running npm run build...
call npm run build
echo Cleaning up...
rmdir /S /Q node-v20.12.2-win-x64
del node.zip
rmdir /S /Q node_modules
echo Rebuild Done!
